import { toSha3 } from './utils/utils'; 

export const [MEMBER_ROLE, ADMIN_ROLE, BANNED_ROLE, PAUSER_ROLE, MINTER_ROLE, TIMELOCK_ADMIN_ROLE, PROPOSER_ROLE, EXECUTOR_ROLE] = [
    toSha3("IKONDAO_MEMBER_ROLE"),
    toSha3("IKONDAO_ADMIN_ROLE"),
    toSha3("IKONDAO_BANNED_ROLE"),
    toSha3("IKONDAO_PAUSER_ROLE"),
    toSha3("IKONDAO_MINTER_ROLE"),
    toSha3("TIMELOCK_ADMIN_ROLE"),
    toSha3("PROPOSER_ROLE"),
    toSha3("EXECUTOR_ROLE")
]